# Generated by Django 4.1.6 on 2023-02-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_productimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inActive',
            new_name='active',
        ),
    ]
