# Generated by Django 4.1.6 on 2023-02-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_inactive_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='productImages',
        ),
        migrations.AddField(
            model_name='product',
            name='productImages',
            field=models.ManyToManyField(to='shop.productimages'),
        ),
    ]
