# Generated by Django 4.1.6 on 2023-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_shipping_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='imgHash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
