# Generated by Django 4.1.6 on 2023-02-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productimages_imghash'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customId',
            field=models.CharField(blank=True, default='WEB-00001', max_length=255, null=True),
        ),
    ]
