# Generated by Django 4.1.6 on 2023-02-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shipping_first_name_alter_shipping_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
