# Generated by Django 4.1.6 on 2023-02-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shipping_lastname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
