# Generated by Django 4.1.6 on 2023-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('HOLD', 'HOLD'), ('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='supportId',
            field=models.CharField(blank=True, default='VEC-00001', max_length=200, null=True),
        ),
    ]
